version: '3.8'
services:
  backend:
    build: ./pratica-backend-main
    ports:
      - "8080:8080"
    environment:
    volumes:
      - ./pratica-backend-main:/app
  frontend:
    build: ./pratica-frontend-main
    ports: 
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./pratica-frontend-main:/app
    environment:
      - API_URL=http://backend:8080